# Generated by Django 4.0.4 on 2022-05-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_orderitem_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='assigned',
            new_name='courier',
        ),
    ]
