# Generated by Django 4.0.4 on 2022-05-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_rename_payment_order_payed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payed',
            new_name='paid',
        ),
    ]
