# Generated by Django 4.0.4 on 2022-05-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_rename_payed_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='x@masmad.com', max_length=254),
            preserve_default=False,
        ),
    ]
