# Generated by Django 4.0.4 on 2022-05-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=1234567890, max_length=50),
            preserve_default=False,
        ),
    ]
