# Generated by Django 4.0.4 on 2022-05-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_order_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='pescription',
            field=models.FileField(null=True, upload_to='files/pescriptions'),
        ),
    ]
