# Generated by Django 4.0.4 on 2022-05-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_remove_order_price_alter_order_pescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
    ]
