# Generated by Django 4.0.4 on 2022-05-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_remove_order_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
